feat: add ecs wait command

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -180,24 +180,97 @@ aws ecs update-service \
   --service "${service_name}" \
   --task-definition "${task_family}:${task_revision}"
 
+############################################################
+# Script begins                                            #
+# https://github.com/misterjoshua/ecs-deployment-wait      #
+############################################################
+
+function log() {
+    echo "$1" >&2
+}
+
+function die() {
+    log "$1"
+    exit 1
+}
+
+function describeService() {
+    SERVICE=$(aws ecs describe-services --cluster "$cluster" --services "$service_name")
+    serviceIsValid <<<"$SERVICE" || return 1
+    cat <<<"$SERVICE"
+}
+
+function serviceIsValid() {
+    [ "true" = "$(jq '.services | length > 0')" ]
+}
+
+function serviceNumPrimary() {
+    jq '[ .services[].deployments[] | select(.status == "PRIMARY") | .runningCount ] | add // 0' --raw-output
+}
+
+function serviceNumActive() {
+    jq '[ .services[].deployments[] | select(.status == "ACTIVE") | .runningCount ] | add // 0' --raw-output
+}
+
+function serviceNumTotal() {
+    jq '[ .services[].deployments[] | .runningCount ] | add // 0' --raw-output
+}
+
+function serviceIsStable() {
+    [ "true" = "$(jq '([.services[].deployments[]] | length == 1) and ([.services[].deployments[] | select(.runningCount == .desiredCount)] | length == 1)')" ]
+}
+
+function now() {
+    date +%s
+}
+
+function waitForDeployment() {
+    TIMEOUT=${TIMEOUT:-300}
+    INTERVAL=${INTERVAL:-5}
+
+    log "Started: Time=$(date), Timeout=$TIMEOUT seconds"
+
+    START_TIME=$(now)
+    while true; do
+        SERVICE=$(describeService)
+        (( $? == 0 )) || die "Couldn't describe the service."
+
+        NUM_PRIMARY=$(serviceNumPrimary <<<$SERVICE)
+        NUM_ACTIVE=$(serviceNumActive <<<$SERVICE)
+        NUM_TOTAL=$(serviceNumTotal <<<$SERVICE)
+        let "ELAPSED=$(now) - START_TIME"
+
+        log "Deployment task counts: Primary=$NUM_PRIMARY, Active=$NUM_ACTIVE, Total=$NUM_TOTAL; Elapsed: $ELAPSED seconds"
+
+        if serviceIsStable <<<$SERVICE; then
+            # Deployment finished
+            return 0
+        elif (( ELAPSED > TIMEOUT )); then
+            log "Timeout $TIMEOUT seconds. (actual: $ELAPSED)"
+            return 1
+        else
+            # Deployment not done yet. Check again in a bit.
+            let "COUNT++"
+            sleep $INTERVAL
+        fi
+    done
+}
+
 ## Now we wait till it's stable
 echo "--- :ecs: Waiting for services to stabilize"
-deploy_exitcode=0
-aws ecs wait services-stable \
-  --cluster "${cluster}" \
-  --services "${service_name}" || deploy_exitcode=$?
 
+exit_code=$( (waitForDeployment && log "Deployment finished." && exit 0) || die "Deployment didn't succeed." )
 
 service_events=$(aws ecs describe-services \
   --cluster "${cluster}" \
   --service "${service_name}" \
   --query 'services[].events' --output text)
 
-if [[ $deploy_exitcode -eq 0 ]]; then
+if [[ $exit_code -eq 0 ]]; then
   echo "--- :ecs: Service is up 🚀"
   echo "$service_events"
 else
   echo "+++ :ecs: Service failed to deploy ❌"
   echo "$service_events"
-  exit $deploy_exitcode
+  exit $exit_code
 fi
